### ISSUE TITLE
求foxyjs源码

### ISSUE THREAD

**Issue by SoftwareEngineeringQ** [darkdragonblade/foxyjs-svgeditor#3]
您的项目非常厉害，我想在您的foxyjs的基础上新增一些操作。
但我只能在npm上下载foxyjs的源码，而下载的源码是经过**压缩处理**的，难以阅读。

1. 压缩了空格
2. 源码中有很多短变量，

请问大佬是否可开源foxyjs的代码，便于二次开发。

**Comment by darkdragonblade** [comment]
首先很感谢您对本项目的关注，本人也有意去发一版您所谓“开源的”版本，同时也鼓励社区的优秀开发者一同去完善这个项目。由于个人时间上的原因没有办法快速去响应您的这个需求，本人近期会考虑逐步解封代码从1.2.33开始，请持续关注更新

**Comment by SoftwareEngineeringQ** [comment]
好的，感谢您的支持

**Comment by jarek-foksa** [comment]
@SoftwareEngineeringQ "foxyjs" code is not readable because most of it was generated by deobfuscating https://boxy-svg.com/app (which is against the licensing terms).
