### ISSUE TITLE
能否支持,自定义vue组件,绑定事件

### ISSUE THREAD

**Issue by shenhaoguangDayDayUp** [darkdragonblade/foxyjs-svgeditor#4]

**Comment by yjm17689263480** [comment]
目前开源已是多兼容模式，可支持vue和react等方式，你的描述可以明确一点吗，或者举个例子

**Comment by shenhaoguangDayDayUp** [comment]
> 目前开源已是多兼容模式，可支持vue和react等方式，你的描述可以明确一点吗，或者举个例子

就是,比方说,我要用到一个svg 或者 一个纯vue 的组件(可以是button,图片,甚至是echarts...等等),把他们封装成一个组件,注册到,这个编辑器里,就可以在这个编辑器里使用他,并且可以绑定事件

**Comment by shenhaoguangDayDayUp** [comment]
> > 就是,比方说,我要用到一个svg 或者 一个纯vue 的组件(可以是button,图片,甚至是echarts...等等),把他们封装成一个组件,注册到,这个编辑器里,就可以在这个编辑器里使用他,并且可以绑定事件
> 
> 在最新版本的foxy中在初始化完成后可以通过javascript原生的方法将自定义的svg,button,image甚至是echarts等等加入到编辑器中，调用方法： const container = document.getElementById("container"); const stage = new Stage(container, { manualGuides: true, smartGuides: true, showGrid: true, showGrid: true, showRulers: true }); stage.htmlPlugins.append(期望加入的元素) ps：值得一提的是，加入后的dom应将初始值设置为 position:absolute; left:1000000px; top:1000000px;
好的,谢谢大佬
